// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXYANi7h6oLwxJbDSxiQNb0f1gHJcDQ84',
    appId: '1:132819485781:web:6c5d28a0395ae47ec8c0dc',
    messagingSenderId: '132819485781',
    projectId: 'weighttracker-9c3c9',
    authDomain: 'weighttracker-9c3c9.firebaseapp.com',
    storageBucket: 'weighttracker-9c3c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoCc7U8iLKmLL-ab8MLmwlv0iaLFUtRqs',
    appId: '1:132819485781:android:71a38dace1da8cb6c8c0dc',
    messagingSenderId: '132819485781',
    projectId: 'weighttracker-9c3c9',
    storageBucket: 'weighttracker-9c3c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7gvUcukzL-yCRcBypyEvQfmfHrqA-iPU',
    appId: '1:132819485781:ios:24175a3801070e69c8c0dc',
    messagingSenderId: '132819485781',
    projectId: 'weighttracker-9c3c9',
    storageBucket: 'weighttracker-9c3c9.appspot.com',
    iosClientId: '132819485781-bea668vdc1p7ea2s1ca7clh3jm8lf5bd.apps.googleusercontent.com',
    iosBundleId: 'com.example.weightTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7gvUcukzL-yCRcBypyEvQfmfHrqA-iPU',
    appId: '1:132819485781:ios:24175a3801070e69c8c0dc',
    messagingSenderId: '132819485781',
    projectId: 'weighttracker-9c3c9',
    storageBucket: 'weighttracker-9c3c9.appspot.com',
    iosClientId: '132819485781-bea668vdc1p7ea2s1ca7clh3jm8lf5bd.apps.googleusercontent.com',
    iosBundleId: 'com.example.weightTracker',
  );
}
